# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l vi -video data/noise.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video data/python.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video data/tt_chinhtri.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video data/tt_suckhoe.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video data/tt_thethao.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary random -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary reduction -sentence 2
# python3 recognize_final.py -l en -video data/en.mp4 -noise deep -summary kl -sentence 2