# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/1.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/2.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/3.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/4.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/5.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/6.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/7.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/8.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/9.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/10.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/11.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/12.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/13.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/14.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/15.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/16.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/17.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/18.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/19.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/20.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/21.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/22.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/23.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/24.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/25.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/26.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/27.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/28.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/29.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/30.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/31.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/32.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/33.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/34.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/35.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/36.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/37.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/38.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/39.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/40.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/41.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/42.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/43.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/44.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/45.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/46.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/47.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/48.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/49.mp4 -noise deep -summary kl -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary lexrank -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary textrank -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary lsa -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary luhn -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary edmundson -sentence 2
# python3 recognize_final.py -l vi -video vi/50.mp4 -noise deep -summary kl -sentence 2


